$endpoints=Hash.new()

# $endpoints[:dbpedia] = "http://dbpedia.org/sparql?default-graph-uri=http://dbpedia.org"
$endpoints[:dbpedia_wis] = "http://wisserver.st.ewi.tudelft.nl:8897/sparql?default-graph-uri=http://dbpedia.org"
$endpoints[:dbpedia_local] = "http://localhost:8894/sparql?default-graph-uri=http://dbpedia.org"
$endpoints[:dbpedialod] = "http://lod.openlinksw.com/sparql?default-graph-uri=http://dbpedia.org"
$endpoints[:dbpedia] = "http://dbpedia.org/sparql?default-graph-uri=http://dbpedia.org"
$endpoints[:dbpedia_ams] = "http://ec2-50-17-66-55.compute-1.amazonaws.com/sparql?default-graph-uri=http://dbpedia.org"
# $endpoints[:geonames]="http://wisserver.st.ewi.tudelft.nl:8892/sparql?default-graph-uri=http://geonames.org"
$endpoints[:imdb]="http://localhost:8896/sparql?default-graph-uri=http://imdb.org"
$endpoints[:nytimes]="http://localhost:8890/sparql?default-graph-uri=http://nytimes.org"
$endpoints[:freebase]="http://localhost:8895/sparql?default-graph-uri=http://freebase.org"
$endpoints[:person11]="http://localhost:8891/sparql?default-graph-uri=http://person11.org"
$endpoints[:person12]="http://localhost:8891/sparql?default-graph-uri=http://person12.org"
$endpoints[:drugbank]="http://localhost:8891/sparql?default-graph-uri=http://drugbank.org"
$endpoints[:sider]="http://localhost:8891/sparql?default-graph-uri=http://sider.org"
$endpoints[:dailymed]="http://localhost:8891/sparql?default-graph-uri=http://dailymed.org"
$endpoints[:geonames]="http://localhost:8898/sparql?default-graph-uri=http://geonames.org"
$endpoints[:enipedia]="http://localhost:8896/sparql?default-graph-uri=http://enipedia.org"
$endpoints[:egrid]="http://localhost:8896/sparql?default-graph-uri=http://egrid.org"
$endpoints[:sider]="http://localhost:8891/sparql?default-graph-uri=http://sider.org"
$endpoints[:drugbank]="http://localhost:8891/sparql?default-graph-uri=http://drugbank.org"
$endpoints[:diseasome]="http://localhost:8891/sparql?default-graph-uri=http://diseasome.org"
$endpoints[:tcm]="http://localhost:8891/sparql?default-graph-uri=http://tcm.org"
$endpoints[:dailymed]="http://localhost:8891/sparql?default-graph-uri=http://dailymed.org"
$endpoints[:restaurant1]="http://localhost:8891/sparql?default-graph-uri=http://restaurant1.org"
$endpoints[:restaurant2]="http://localhost:8891/sparql?default-graph-uri=http://restaurant2.org"
$endpoints[:person21]="http://localhost:8891/sparql?default-graph-uri=http://person21.org"
$endpoints[:person22]="http://localhost:8891/sparql?default-graph-uri=http://person22.org"
